Repository HappyDevelopers-team7/team7-taskify, pull requests merged in 2024-03, with the labels that each got.

#21 ✨대시보드 사이드바
  public/assets/image/icons/arrowForwardIcon(gray).svg
  public/assets/image/icons/arrowForwardIcon(gray-left).svg
  public/assets/image/icons/arrowForwardIcon(left).svg
  public/assets/image/logos/sideLogo.png
  src/components/side-menu/index.tsx
  src/components/side-menu/style.ts
  src/pages/dashboard/index.tsx
Labels: 퍼블리싱, 기능구현, 대시보드 페이지

#23 FEAT: 로그인 회원가입 기능 구현 (쿠키 저장까지)
  package-lock.json
  package.json
  public/assets/image/icons/checkWhiteIcon.svg
  src/api/instance/axiosInstance.ts
  src/api/postSignIn.ts
  src/api/postSignUp.ts
  src/components/full-button/index.tsx
  src/components/full-button/style.ts
  src/constants/message/index.ts
  src/constants/regex/index.ts
  src/hooks/useAsync.ts
  src/main.tsx
  src/pages/dashboard-test/index.tsx
  src/pages/dashboard-test/style.ts
  src/pages/sign-in/index.tsx
  src/pages/sign-in/style.ts
  src/pages/sign-up/index.tsx
  src/redux/store.ts
  src/redux/userActions.ts
  src/redux/userSlice.ts
  src/routes/routes.tsx
  src/styles/reset/resetCss.ts
  src/utils/check-regex/checkRegex.ts
Labels: 퍼블리싱, 기능구현, 로그인/회원가입 패이지

#25 CHORE: 회원가입 비동기 훅 수정
  src/api/postSignUp.ts
  src/pages/sign-up/index.tsx
Labels: 리펙토링, 로그인/회원가입 패이지

#27 CHORE: 쿠키 토큰 사용하는 방법 예시 코드 작성 / 리덕스 데브 툴스 설정 외 기타
  index.html
  package-lock.json
  package.json
  src/api/getMyInfo.ts
  src/api/instance/axiosInstance.ts
  src/pages/dashboard-test/index.tsx
  src/redux/store.ts
  src/routes/loading/index.tsx
Labels: 퍼블리싱, 로그인/회원가입 패이지, 기타 페이지

#29 Feature 반응형사이드메뉴
  public/assets/image/logos/sideLogo.png
  src/api/constants/index.ts
  src/components/side-menu/index.tsx
  src/pages/dashboard/index.tsx
Labels: 리펙토링, 대시보드 페이지

#32 7 feat 헤더 UI 완성시키기
  src/components/dashboardHeader/index.tsx
  src/components/dashboardHeader/style.ts
  src/components/side-menu/style.ts
  src/pages/dashboard/index.tsx
Labels: 퍼블리싱, 대시보드 페이지

#33 FEAT: 리덕스 툴킷 비동기 처리
  src/api/getMyInfo.ts
  src/api/instance/axiosInstance.ts
  src/main.tsx
  src/pages/dashboard-test/index.tsx
  src/pages/sign-in/index.tsx
  src/redux/myInfoSlice.ts
  src/redux/store/store.ts
  src/redux/userActions.ts
  src/redux/userSlice.ts
Labels: 기능구현, 기타 페이지

#36 CHORE: 헤더 확인해서 main 태그 공통으로 들어간 부분 삭제
  src/routes/loading/index.tsx
Labels: 퍼블리싱, 기타 페이지

#39 CHORE: 레이아웃 컴포넌트 생성
  src/components/dashboardHeader/style.ts
  src/components/side-menu/style.ts
  src/pages/dashboard/index.tsx
  src/routes/layout/index.tsx
  src/routes/layout/style.ts
  src/routes/protected-routes/index.tsx
  src/routes/routes.tsx
Labels: 기능구현, 기타 페이지

#40 FEAT: 대시보드{id}페이지
  public/assets/image/icons/bannerAddIcon.svg
  src/api/constants/index.ts
  src/components/add-column-button/index.tsx
  src/components/add-column-button/style.ts
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/side-menu/index.tsx
  src/components/side-menu/style.ts
  src/pages/dashboard-id/index.tsx
  src/pages/dashboard-id/style.ts
  src/routes/layout/style.ts
  src/routes/routes.tsx
Labels: 퍼블리싱, 기능구현, 대시보드 id 페이지

#44 FEAT: 모달 컴포넌트 수정 + input text 컴포넌트화 (반응형 O)
  src/components/auth-input/index.tsx
  src/components/auth-input/style.ts
  src/components/full-button/fullButtonType.ts
  src/components/full-button/index.tsx
  src/components/full-button/style.ts
  src/components/input/input-text/index.tsx
  src/components/input/input-text/style.ts
  src/components/modal-container/index.tsx
  src/components/modal-container/style.ts
  src/components/modal-contents/create-dashboard-modal/style.ts
  src/components/modal-contents/create-dashboard/index.tsx
  src/components/modal-contents/create-dashboard/style.ts
  src/constants/message/index.ts
  src/pages/dashboard/index.tsx
  src/pages/dashboard/style.ts
  src/styles/input/style.ts
Labels: 퍼블리싱, 기능구현, 대시보드 페이지

#47 💄 컬럼에서 + 누르면 모달뜨게
  package-lock.json
  package.json
  public/assets/image/icons/modalAddIcon.svg
  src/api/constants/index.ts
  src/components/card/index.tsx
  src/components/card/style.ts
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/side-menu/index.tsx
  src/components/side-menu/style.ts
  src/pages/dashboard-id/index.tsx
Labels: 퍼블리싱, 대시보드 id 페이지

#49 FEAT: modal 오류 수정 / 대시보드 리스트, 초대하기 기능 연결
  src/api/constants/index.ts
  src/api/getDashboardList.ts
  src/api/getInvitation.ts
  src/api/instance/axiosInstance.ts
  src/components/Invited-list/index.tsx
  src/components/Invited-list/style.ts
  src/components/input/input-search/index.tsx
  src/components/input/input-search/style.ts
  src/components/my-dashboard-list-item/index.tsx
  src/components/my-dashboard-list-item/style.ts
  src/components/my-dashboard-list/index.tsx
  src/components/no-invitation/index.tsx
  src/components/no-invitation/style.ts
  src/components/side-menu/style.ts
  src/constants/message/index.ts
  src/pages/dashboard/index.tsx
  src/redux/modalSlice.ts
  src/routes/layout/index.tsx
  src/routes/layout/style.ts
  src/styles/reset/resetCss.ts
Labels: 퍼블리싱, 리펙토링, 기능구현, 대시보드 페이지, 리덕스 툴킷

#51 CHORE: 모달 수정이 안올라가서 다시 생성
  package-lock.json
  package.json
  src/redux/modalSlice.ts
  src/routes/layout/index.tsx
Labels: 리펙토링, 리덕스 툴킷

#57 7 feat 헤더 UI 완성시키기
  src/api/constants/index.ts
  src/components/dashboardHeader/index.tsx
  src/components/dashboardHeader/style.ts
  src/redux/myInfoSlice.ts
Labels: 퍼블리싱, 기능구현, 기타 페이지

#60 FEAT: 대시 보드 오류 수정 + 페이지네이션 + 초대 수락/거절 등
  public/assets/image/icons/arrowForwardIconGray.svg
  public/assets/image/icons/arrowForwardIconGrayLeft.svg
  public/assets/image/icons/arrowForwardIconLeft.svg
  src/api/putInviteAccepted.ts
  src/components/invitation-list/index.tsx
  src/components/invitation-list/style.ts
  src/components/modal-container/index.tsx
  src/components/modal-contents/accept-invitation/index.tsx
  src/components/modal-contents/accept-invitation/style.ts
  src/components/modal-contents/create-dashboard/index.tsx
  src/components/modal-contents/reject-invitation/index.tsx
  src/components/modal-contents/reject-invitation/style.ts
  src/components/my-dashboard-list/index.tsx
  src/components/my-dashboard-list/style.ts
  src/components/side-menu/index.tsx
  src/constants/message/index.ts
  src/main.tsx
  src/pages/dashboard-id/index.tsx
  src/pages/dashboard/index.tsx
  src/redux/dashboardListSlice.ts
  src/redux/invitationSlice.ts
  src/redux/modalSlice.ts
  src/routes/layout/style.ts
  src/utils/removeDuplicates.ts
Labels: 리펙토링, 기능구현, 대시보드 페이지, 리덕스 툴킷

#62 FEAT: 대시보드 무한 스크롤 구현하기
  public/assets/image/icons/bannerLogoIconS.svg
  src/api/getInvitation.ts
  src/components/invitation-list/index.tsx
  src/components/invitation-list/style.ts
Labels: 기능구현, 대시보드 페이지

#64 Feature 대시보드{id}페이지
  package-lock.json
  package.json
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/side-menu/index.tsx
  src/components/tag-component/index.tsx
  src/components/tag-component/style.ts
  src/pages/dashboard-id/index.tsx
  src/pages/dashboard-id/style.ts
  src/utils/dateExtractor.ts
  src/utils/randomHexCode.ts
Labels: 기능구현, 대시보드 id 페이지

#66 🧹 모달 높이 수정
  src/components/column/style.ts
Labels: 퍼블리싱, 리펙토링

#67 CHORE: 사이드 메뉴에 대시보드 생성 모달 넣기
  index.html
  netlify.toml
  public/assets/image/icons/favicon.ico
  src/api/getSideDashboardList.ts
  src/components/invitation-list/index.tsx
  src/components/modal-container/index.tsx
  src/components/modal-contents/create-dashboard/index.tsx
  src/components/my-dashboard-list/index.tsx
  src/components/side-menu/index.tsx
  src/redux/dashboardListSlice.ts
Labels: 리펙토링, 기타 페이지

#71 배포를 위한 메타 태그 이미지 경로 변경
  index.html
Labels: 배포

#78 FEAT: 대시보드{id} 페이지에서 카드 출력
  src/components/add-column-button/index.tsx
  src/components/card/index.tsx
  src/components/card/style.ts
  src/components/column/index.tsx
  src/components/column/style.ts
Labels: 퍼블리싱, 기능구현, 대시보드 id 페이지

#84 FEAT: 더보기 버튼
  src/components/add-column-button/index.tsx
  src/components/card/style.ts
  src/components/column/index.tsx
  src/components/column/style.ts
Labels: 리펙토링, 기능구현, 대시보드 id 페이지

#86 대시보드 멤버들 띄우기 & 프로필 드롭다운 ( 계정관리 페이지버튼 & 로그아웃 버튼) 완료!
  src/components/dashboardHeader/index.tsx
  src/components/dashboardHeader/style.ts
Labels: 퍼블리싱, 기능구현, 기타 페이지

#91 #85 my page 퍼블리싱 완료, 기능 미완성
  public/assets/image/icons/addIconPurple.svg
  public/assets/image/icons/backArrowIcon.svg
  src/api/postProfileImage.ts
  src/api/putUserInformation.ts
  src/components/dashboardHeader/index.tsx
  src/components/modal-edit-column/index.tsx
  src/pages/my-page/index.tsx
  src/pages/my-page/style.ts
  src/routes/routes.tsx
Labels: 마이페이지 패이지, 퍼블리싱

#92 FEAT: 댓글 무한 스크롤카드 삭제시 성공값 못 받아오는 오류
  src/api/deleteCard.ts
  src/api/getComments.ts
  src/components/card/index.tsx
  src/components/dashboardHeader/index.tsx
  src/components/detail-comment-area/index.tsx
  src/components/detail-comment-area/style.ts
  src/components/invitation-list/index.tsx
  src/components/modal-add-column/index.tsx
  src/components/modal-contents/card-detail/index.tsx
  src/components/modal-contents/card-detail/style.ts
  src/components/modal-contents/edit-card/index.tsx
  src/constants/message/index.ts
  src/pages/dashboard-id/style.ts
  src/routes/layout/style.ts
Labels: 리펙토링, 기능구현, 대시보드 페이지, 대시보드 id 페이지

#94 Feat : 초대하기 모달 띄우기 & 기능
  src/api/postInviteDashboard.ts
  src/components/dashboard-Header/index.tsx
  src/components/dashboard-Header/style.ts
  src/components/modal-contents/invite-dashboard/index.tsx
  src/components/modal-contents/invite-dashboard/style.ts
  src/constants/message/index.ts
  src/routes/layout/index.tsx
Labels: 기능구현, 기타 페이지

#98 FEAT: 할 일 수정 모달
  public/assets/image/icons/checkIcon.svg
  public/assets/image/icons/removeIcon.svg
  src/components/card/index.tsx
  src/components/card/style.ts
  src/components/column-name-tag/index.tsx
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/modal-contents/card-detail/index.tsx
  src/components/modal-contents/create-card/index.tsx
  src/components/modal-contents/create-card/style.ts
  src/components/modal-contents/edit-card/index.tsx
  src/components/modal-contents/edit-card/style.ts
  src/components/tag-component/index.tsx
  src/pages/dashboard-id/index.tsx
  src/types/cardDetailType.ts
  src/types/cardObjectType.ts
  src/types/columnDetailTypes.ts
  src/types/dashboardIdTypes.ts
Labels: 기능구현, 대시보드 id 페이지

#101 Develop - 배포
  public/assets/image/icons/checkIcon.svg
  public/assets/image/icons/removeIcon.svg
  src/components/card/index.tsx
  src/components/card/style.ts
  src/components/column-name-tag/index.tsx
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/modal-contents/card-detail/index.tsx
  src/components/modal-contents/create-card/index.tsx
  src/components/modal-contents/create-card/style.ts
  src/components/modal-contents/edit-card/index.tsx
  src/components/modal-contents/edit-card/style.ts
  src/components/tag-component/index.tsx
  src/pages/dashboard-id/index.tsx
  src/pages/dashboard/style.ts
  src/pages/my-page/style.ts
  src/styles/common-height/style.ts
  src/types/cardDetailType.ts
  src/types/cardObjectType.ts
  src/types/columnDetailTypes.ts
  src/types/dashboardIdTypes.ts
Labels: 배포

#102 CHORE: modal-add-column 오류 수정
  src/components/modal-add-column/index.tsx
Labels: 배포

#111 Develop - page not found 추가 / 모달 컨테이너 스타일 수정
  public/assets/image/logos/errorLogo.svg
  src/components/modal-container/style.ts
  src/pages/not-found/index.tsx
  src/pages/not-found/style.ts
Labels: 퍼블리싱, 기타 페이지

#103 CHORE: 할 일 수정 모달 버그픽스, 컬럼파일에서 모달 분리
  src/api/postCreateCard.ts
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/modal-contents/create-card/index.tsx
  src/components/modal-contents/create-card/style.ts
  src/components/modal-contents/edit-card/index.tsx
  src/components/modal-contents/edit-card/style.ts
Labels: 리펙토링, 대시보드 id 페이지

#105 대시보드 color & title 변경 컴포넌트 완료
  .github/ISSUE_TEMPLATE/이슈-생성-탬플릿.md
  src/api/getDashboardInfo.ts
  src/api/putDashboardChange.ts
  src/components/dashboard-Header/index.tsx
  src/components/dashboard-Header/style.ts
  src/components/edit-dashboardtitleAndcolorchanger/index.tsx
  src/components/edit-dashboardtitleAndcolorchanger/style.ts
  src/constants/message/index.ts
  src/pages/dashboard-edit/index.tsx
  src/pages/dashboard-edit/style.ts
  src/styles/theme/theme.ts
Labels: 퍼블리싱, 기능구현, 대시보드 관리 패이지

#117 CHORE: alert을 toast로 대체 외 2건
  src/components/modal-contents/create-card/index.tsx
  src/components/modal-contents/create-card/style.ts
  src/components/modal-contents/edit-card/index.tsx
  src/pages/dashboard-id/index.tsx
Labels: 리펙토링, 대시보드 id 페이지

#121 CHORE : 헤더 수정
  src/components/dashboard-Header/index.tsx
  src/components/dashboard-Header/style.ts
  src/styles/theme/theme.ts
Labels: 리펙토링, 기타 페이지

#122 REFACTOR: 카드를 다른 컬럼으로 옮겼을때 새로고침없이 화면 리렌더링
  src/components/card/index.tsx
  src/components/column/index.tsx
  src/components/modal-contents/create-card/index.tsx
  src/components/modal-contents/edit-card/index.tsx
  src/pages/dashboard-id/index.tsx
  src/types/cardObjectType.ts
Labels: 리펙토링, 대시보드 id 페이지

#128 100 대시보드 관리 페이지 구현
  package-lock.json
  package.json
  src/api/deleteDashboard.ts
  src/api/deleteDashboardInvite.ts
  src/api/deleteDashboardMember.ts
  src/api/getDashboardInviteList.ts
  src/api/getDashboardMemberList.ts
  src/components/arrow_button/index.tsx
  src/components/arrow_button/style.ts
  src/components/backbutton/index.tsx
  src/components/backbutton/style.ts
  src/components/dashboard-Header/index.tsx
  src/components/dashboard-Header/style.ts
  src/components/edit-dashboard-invite-list/index.tsx
  src/components/edit-dashboard-invite-list/style.ts
  src/components/edit-dashboard-member-list/index.tsx
  src/components/edit-dashboard-member-list/style.ts
  src/components/edit-dashboardtitleAndcolorchanger/index.tsx
  src/components/edit-dashboardtitleAndcolorchanger/style.ts
  src/components/edit-delete-button/index.tsx
  src/components/edit-delete-button/style.ts
  src/components/edit-title-color-changer/index.tsx
  src/components/edit-title-color-changer/style.ts
  src/components/input/input-text/index.tsx
  src/pages/dashboard-edit/index.tsx
  src/pages/dashboard-edit/style.ts
  src/routes/routes.tsx
Labels: 퍼블리싱, 기능구현, 대시보드 관리 패이지

#131 100 대시보드 관리 페이지 구현
  src/components/edit-dashboard-member-list/index.tsx
  src/components/edit-title-color-changer/index.tsx
  src/components/edit-title-color-changer/style.ts
Labels: 퍼블리싱, 기능구현, 대시보드 관리 패이지

#129 85 my page 구현
  src/components/landing-header/style.ts
  src/components/modal-add-column/style.ts
  src/components/modal-edit-column/index.tsx
  src/pages/my-page/style.ts
Labels: 마이페이지 패이지, 퍼블리싱

#132 STYLE: 사이드바, 대시보드ID페이지 반응형 구현
  src/components/add-column-button/style.ts
  src/components/card/index.tsx
  src/components/card/style.ts
  src/components/column/index.tsx
  src/components/column/style.ts
  src/components/modal-contents/create-card/style.ts
  src/components/modal-contents/edit-card/style.ts
  src/components/side-menu/index.tsx
  src/components/side-menu/style.ts
  src/components/tag-component/style.ts
  src/pages/dashboard-id/index.tsx
  src/pages/dashboard-id/style.ts
  src/routes/layout/style.ts
Labels: 퍼블리싱, 리펙토링, 대시보드 id 페이지

#134 대시보드 멤버 삭제 & 이메일 추가 컴포넌트 수정
  src/api/postInviteDashboard.ts
  src/components/edit-dashboard-invite-list/index.tsx
  src/components/edit-dashboard-member-list/index.tsx
Labels: 퍼블리싱, 기능구현, 대시보드 관리 패이지

#135 Develop - 배포
  src/api/postInviteDashboard.ts
  src/components/edit-dashboard-invite-list/index.tsx
  src/components/edit-dashboard-member-list/index.tsx
  src/components/modal-contents/accept-invitation/index.tsx
Labels: 배포
